services:
  client-react:
    build:
      context: .
      args:
        REACT_APP_SERVER_URL: ${REACT_APP_SERVER_URL}
    image: samarkinivan/messenger-client:latest
    container_name: messenger-client
    restart: on-failure
    env_file: .env
    ports:
      - '3000:80'
